apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-od-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harunisiaho/argocd-gitops.git
    targetRevision: HEAD
    paths:
    - ./dev/app
    - ./staging/app
    - ./prod/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
